### ISSUE TITLE
Bundle Install Error

### ISSUE THREAD

**Issue by pearlymaccha** [heroku/ruby-getting-started#10]
Hello, I try to run 'bundle install' but I got this result:
![11 error bundle install](https://cloud.githubusercontent.com/assets/6280032/8395604/0cf45be0-1da5-11e5-8700-6b4f6973892c.JPG)

Then I run 'gem install pg -v '0.17.1' '
The result is:

Building native extensions.  This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150628-12053-kbx4ef.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-pg
        --without-pg
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
/usr/local/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1113:in `block in find_header'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /usr/local/lib/ruby/2.2.0/mkmf.rb:1112:in `find_header'
        from extconf.rb:48:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/pg-0.17.1 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/pg-0.17.1/gem_make.out

Can someone help me please? Thanks.

**Comment by jonmountjoy** [comment]
You need to install Postgres.  When done right, you'll end up with `pg_config` in your path, and the gem should install.

**Comment by pearlymaccha** [comment]
Thank you @jonmountjoy. I've fixed this problem by adding library of postgres -> sudo apt-get install libpq-dev
