### ISSUE TITLE
Changing logger level has no effect

### ISSUE THREAD

**Issue by vfonic** [heroku/ruby-getting-started#49]
I've been struggling with this issue for more than I should. :)

I just wanted to check that this issue is also happening in this repo.

Here it is fully explained:
https://github.com/heroku/rails_12factor/issues/32

Thank you!

**Comment by vfonic** [comment]
I changed this line and deployed: `config.log_level = :warn`

I still see the logs like these when I run `heroku logs`:

> 2019-04-24T05:45:58.430769+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=stormy-bastion-37507.herokuapp.com request_id=74b4be38-aa04-434f-8d5c-c257a1994c6b fwd="183.88.37.135" dyno=web.1 connect=0ms service=1ms status=304 bytes=48 protocol=https

**Comment by schneems** [comment]
This repo does not use rails_12factor https://github.com/heroku/ruby-getting-started/commit/a47c521e953655340c7b25730b480c1739bbb26b

Are you able to change your logging level locally?
